# ========== Profile ========== #
# avatar
avatar: /images/avatar1.png
# author name
author: chris kwok
# signature
signature: Run.
# SNS
social:
  email: baozaodexianyu@163.com
  github: //github.com/rollawaypoint
  # wechat and qq should be a path of qr-code image
  wechat: /images/wechat.png
  weibo: https://weibo.com/577117087
  zhihu: 
  twitter: 
  instagram: 
  bilibili: 
  rss: /atom.xml
social_icons:
  enable: true
  # Icon Mappings
  GitHub: github
  Twitter: twitter
  å¾®åš: weibo
# friends
friends:
  æ˜é‡‘ä¸»é¡µ: 
  ç®€ä¹¦: 
  friendC: 
  ç½‘æ˜“äº‘éŸ³ä¹: https://music.163.com/#/user/home?id=65978744
about:
  enable: true
  image: 

# ========== Site ========== #
# title of the site
SEO_title: chris kwok
# main title
main_title: christian
# subtitle
subtitle: Run.
# site haeder image
site_header_image: /images/bg_site.jpg
# post haeder image
post_header_image: /images/bg_post.png
# 404 image
_404_image: 'https://source.unsplash.com/random'

# ========== Search ========== #
algolia_search:
  enable: true
  hits:
    per_page: 10 # æ¯é¡µçš„ç»“æœæ•°
  labels:
    input_placeholder: è¾“å…¥æ–‡æ¡£å…³é”®å­—ï¼ # æœç´¢æ  placeholder
    hits_empty: "ä»€ä¹ˆéƒ½æ²¡æ‰¾åˆ°å‘¢ï½" # æœç´¢ç»“æœæç¤º
    hits_stats: "æœç´¢åˆ°äº†${hits}æ¡ç»“æœï¼ ï¼ˆ${time} msï¼‰" # æœç´¢æ— ç»“æœçš„æç¤º

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: 
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid: 
  changyan_conf: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 
  # Valine  site: https://valine.js.org/
  valine_appId: "182xGKUdHzDs4pqBWIanVxsg-gzGzoHsz"
  valine_appKey: "1Fe0jaE38KF5iFsXDY4i8YoO"
  valine_placeHolder: ç»™æˆ‘ä¸ªç•™è¨€å§ï¼
leancloud_visitors:
  enable: true
  app_id:  "182xGKUdHzDs4pqBWIanVxsg-gzGzoHsz"
  app_key:  "1Fe0jaE38KF5iFsXDY4i8YoO"
  # Dependencies:  https://github.com/theme-next/hexo-leancloud-counter-security #è®¾ç½®ä¾èµ–
  security: false #å¦‚æœæ‚¨ä¸å…³å¿ƒlcè®¡æ•°å™¨ä¸­çš„å®‰å…¨æ€§å¹¶ä¸”åªæƒ³ç›´æ¥ä½¿ç”¨å®ƒï¼ˆæ²¡æœ‰hexo-leancloud-counter-securityæ’ä»¶ï¼‰ï¼Œè¯·å°†`security`è®¾ç½®ä¸º`false`ã€‚
  betterPerformance: true #æ›´å¥½çš„æ€§èƒ½

# ========== Analytics ========== #
# enable Busuanzi analytics
busuanzi: true
# fill in pv or uv
busuanzi_pv_or_uv: 'pv'
# custom analytic slogan, '${count}' is the analytic number, DO NOT modify it.
busuanzi_slug: 'PV: ${count} ğŸ‰'
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: UA-112738831-1
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /images/favicon.ico
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# enable toc
toc: true
# word count & reading time
reading_info: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50

# äºŒæ¬¡å…ƒå¯åŠ¨
live2d:
  enable: true
  scriptFrom: local
  model:
    use: live2d-widget-model-gf
  display:    
    position: right
    width: 150
    height: 300
  mobile:
    show: true
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: 'æœ¬æ–‡é‡‡ç”¨<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨ 4.0 å›½é™…è®¸å¯åè®®</a>è¿›è¡Œè®¸å¯'
